package com.example.dc_acconverterandcontrolremote.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFBCFFD5)
val PurpleGrey80 = Color(0xFF48E19B)
val Pink80 = Color(0xFF99AB58)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF1C7477)
val md_theme_light_onPrimary = Color(0xFF796452)
val md_theme_light_primaryContainer = Color(0xFFFFF3DD)
val md_theme_light_onPrimaryContainer = Color(0xFF0F772C)
val md_theme_light_secondary = Color(0xFF6E9A39)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5CE9C)
val md_theme_light_onSecondaryContainer = Color(0xFF1E192B)
val md_theme_light_tertiary = Color(0xFF374DC4)
val md_theme_light_onTertiary = Color(0xFFB5FDB5)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onTertiaryContainer = Color(0xFF171031)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF540306)
val md_theme_light_background = Color(0xFFCDF0F3)
val md_theme_light_onBackground = Color(0xFF002022)
val md_theme_light_surface = Color(0xFFF3FEFF)
val md_theme_light_onSurface = Color(0xFF002022)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF51049D)
val md_theme_light_inverseOnSurface = Color(0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(0xFF00373A)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)
val md_theme_light_surfaceTint = Color(0xFF6B3DD4)
val md_theme_light_outlineVariant = Color(0xFFCAC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF8F81B2)
val md_theme_dark_onPrimary = Color(0xFF3A0092)
val md_theme_dark_primaryContainer = Color(0xFF418329)
val md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_secondary = Color(0xFFCBC2DB)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF4A2525)
val md_theme_dark_tertiaryContainer = Color(0xFF851F2E)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF083E41)
val md_theme_dark_onBackground = Color(0xFF70F5FF)
val md_theme_dark_surface = Color(0xFF002022)
val md_theme_dark_onSurface = Color(0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(0xFF255925)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF02384F)
val md_theme_dark_inverseSurface = Color(0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(0xFF6145A1)
val md_theme_dark_surfaceTint = Color(0xFFCFBCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)